# Generated by Django 4.2.6 on 2023-10-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightroute',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='departure_time',
        ),
    ]
