# Generated by Django 4.2.6 on 2023-10-26 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_remove_flightroute_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroute',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.time(16, 0), help_text='Arrival time'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='departure_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), help_text='Departure time'),
        ),
    ]
