# Generated by Django 4.2.6 on 2023-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(help_text='Route name, e.g., Mumbai-Delhi', max_length=100, unique=True)),
                ('BusinessClassprice', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('PremiumEconomy', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('EconomyClass', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('departure_time', models.TimeField(help_text='Departure time')),
                ('arrival_time', models.TimeField(help_text='Arrival time')),
            ],
            options={
                'verbose_name': 'Flight Route',
                'verbose_name_plural': 'Flight Routes',
            },
        ),
    ]
